export const GET_LIST_MUSIC = "GET_LIST_MUSIC";
export const SUCCESS_GET_LIST_MUSIC = "SUCCESS_GET_LIST_MUSIC";
export const ERROR_GET_LIST_MUSIC = "ERROR_GET_LIST_MUSIC";

export const FETCH_ADD_CALCULATOR = "FETCH_ADD_CALCULATOR";
export const SUCCESS_ADD_CALCULATOR = "SUCCESS_ADD_CALCULATOR";
export const ERROR_ADD_CALCULATOR = "ERROR_ADD_CALCULATOR";